// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PleaseWeb {
	
	
	public partial class AdminSettings {
		
		protected System.Web.UI.WebControls.Content titleContentContent;
		
		protected System.Web.UI.WebControls.Content headerContentContent;
		
		protected System.Web.UI.WebControls.Content contentPlaceHolderContent;
		
		protected System.Web.UI.WebControls.TextBox txtSMTPServer;
		
		protected System.Web.UI.WebControls.TextBox txtPort;
		
		protected System.Web.UI.WebControls.TextBox txtMailFrom;
		
		protected System.Web.UI.WebControls.TextBox txtLinkUrl;
		
		protected System.Web.UI.WebControls.TextBox txtEmailSubjectNewSubscriber;
		
		protected System.Web.UI.WebControls.TextBox txtEmailBodyNewSubscriber;
		
		protected System.Web.UI.WebControls.TextBox txtEmailSubjectNewRequest;
		
		protected System.Web.UI.WebControls.TextBox txtEmailBodyNewRequest;
		
		protected System.Web.UI.WebControls.TextBox txtEmailSubjectRequestAcceptedSubscribers;
		
		protected System.Web.UI.WebControls.TextBox txtEmailBodyRequestAcceptedSubscribers;
		
		protected System.Web.UI.WebControls.TextBox txtEmailSubjectRequestAcceptedRequestor;
		
		protected System.Web.UI.WebControls.TextBox txtEmailBodyRequestAcceptedRequestor;
		
		protected System.Web.UI.WebControls.Button cmdSave;
		
		public new PleaseWeb.Master Master {
			get {
				return ((PleaseWeb.Master)(base.Master));
			}
		}
	}
}
