// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PleaseWeb {
	
	
	public partial class Subscribe {
		
		protected System.Web.UI.WebControls.Content titlePlaceHolderContent;
		
		protected System.Web.UI.WebControls.Content headerPlaceHolderContent;
		
		protected System.Web.UI.WebControls.Content contentPlaceHolderContent;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox txtSMS;
		
		protected System.Web.UI.WebControls.Button cmdSubscribe;
		
		public new PleaseWeb.Master Master {
			get {
				return ((PleaseWeb.Master)(base.Master));
			}
		}
	}
}
